
DROP VIEW IF EXISTS [$(PROJECT_SCHEMA_NAME)].[V_PBI_10988_TECHNICAL_ACT_P1]
GO

DROP VIEW IF EXISTS [$(PROJECT_SCHEMA_NAME)].[V_PBI_10988_TECHNICAL_ACT_P1_ACTUAL_DATE]
GO

DROP VIEW IF EXISTS [$(PROJECT_SCHEMA_NAME)].[V_PBI_10988_TECHNICAL_ACT_P1_ASUT_DATE]
GO